### ISSUE TITLE
Cloud Requests TypeError

### ISSUE THREAD

**Issue by programORdie2** [TimMcCool/scratchattach#103]
Warning: Caught error in request 'load' - Full error below
Traceback (most recent call last):
  File "C:\Users\philippechristl\AppData\Local\Programs\Python\Python311\Lib\site-packages\scratchattach\_cloud_requests.py", line 100, in call_request
    output = req_obj["on_call"](*arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\philippechristl\Documents\1scratch\AI_IMAGE_super.py", line 142, in load
    user = client.get_requester()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\philippechristl\AppData\Local\Programs\Python\Python311\Lib\site-packages\scratchattach\_cloud_requests.py", line 170, in get_requester
    activity = list(
               ^^^^^
  File "C:\Users\philippechristl\AppData\Local\Programs\Python\Python311\Lib\site-packages\scratchattach\_cloud_requests.py", line 171, in <lambda>
    filter(lambda x: "." + self.last_request_id in x["value"],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by programORdie2** [comment]
`
def load():
    user = client.get_requester()
    print(user, 'requsted')
    return 'ok'
`

**Comment by programORdie2** [comment]
Huh? Wait, after restarting the code a few times, it works. 
`WEIRD`
