### ISSUE TITLE
The get variable command fails on one variable only

### ISSUE THREAD

**Issue by NumbersTada** [TimMcCool/scratchattach#111]
Traceback (most recent call last):
  File "E:\Táda\Plocha\Systém Táďos\Stažené soubory\Comment-Filter-Bypass-main\Comment-Filter-Bypass-main\comment.py", line 29, in <module>
    username = Encoding.decode(scratch3.get_var(pid, "pw"))
  File "C:\Users\TAĎAS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scratchattach\_encoder.py", line 119, in decode
    letter = letters[int(f"{inp[i*2]}{inp[(i*2)+1]}")]
ValueError: invalid literal for int() with base 10: 'No'

**Comment by TimMcCool** [comment]
scratch3.get_var(pid, "pw") seems to return None. Are you sure you specified the correct project id, and does the "pw" cloud variable actually exist? Has it been set since it was created?

**Comment by NumbersTada** [comment]
> scratch3.get_var(pid, "pw") seems to return None. Are you sure you specified the correct project id, and does the "pw" cloud variable actually exist? Has it been set since it was created?

yes
