### ISSUE TITLE
`ConnectionError` with `[SSL: CERTIFICATE_VERIFY_FAILED]` during `connect_cloud`

### ISSUE THREAD

**Issue by xnousnow** [TimMcCool/scratchattach#126]
```python
import scratchattach as scratch3

session = scratch3.Session(
    '".[my session id]"',
    username="xnousnow",
)
conn = session.connect_cloud("880600510")  # Error
```
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 67, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 77, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/route/hidden/for/privacy/main.py", line 10, in <module>
    conn = session.connect_cloud("880600510")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_session.py", line 248, in connect_cloud
    return _cloud.CloudConnection(username = self._username, session_id = self.session_id, project_id = int(project_id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 24, in __init__
    self._connect(cloud_host=cloud_host)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 85, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError
```
I get an `ConnectionError` with `[SSL: CERTIFICATE_VERIFY_FAILED]` during `connect_cloud` function. I have good internet connection, and I use Mac. I ran this locally and got this error every time I try to run it. I alternatively tried `scratch3.login` function to replace `scratch3.Session`, and that gave me the same error.

**Comment by programORdie2** [comment]
You need to remove the " in your sessionID.

**Comment by TimMcCool** [comment]
Seems to be the same issue as #96. I can't reproduce the issue unfortunately, it's working fine on all of my devices

**Comment by TimMcCool** [comment]
What OS are you using, where are you running the code?

**Comment by xnousnow** [comment]
MacOS, python3 and pip3, zsh for terminal. All are updated to the latest version. I will try # 96.

**Comment by oppoipoi** [comment]
I got the same issue on my mac

**Comment by GitbyteMaster** [comment]
Me too, on my Mac

**Comment by mas6y6** [comment]
I got it as well and I somehow fixed it is just i forget out to do it

**Comment by mas6y6** [comment]
Hey tim what does scratchattach use to connect to scratch cloud varables database

**Comment by TimMcCool** [comment]
> Hey tim what does scratchattach use to connect to scratch cloud varables database

it connects to the websocket using the websocket-client module. For more info, see the scratchattach/cloud.py file in this github repo
