### ISSUE TITLE
Can't get comments

### ISSUE THREAD

**Issue by crzylemon** [TimMcCool/scratchattach#192]
Full error:
```
Traceback (most recent call last):
  File "C:\Users\-------\Documents\Scratchattach\testing commenta.py", line 5, in <module>
    current = project.comments(limit=5, offset=0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-------\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\project.py", line 294, in comments
    comments = comments + r
               ~~~~~~~~~^~~
TypeError: can only concatenate list (not "dict") to list
```
I connected to project and logged in, what's happening?

EDIT: Here's the code:
```
import scratchattach as scratch3
session = scratch3.login("disnottaken_alt", password removed by TimMcCool)
project =  session.connect_project("996647443")

current = project.comments(limit=5, offset=0)
print(current) #should work?
```

**Comment by RC9910-Scratch** [comment]
pls don't share password

**Comment by TimMcCool** [comment]
might be a bug, I'll look into it

**Comment by TimMcCool** [comment]
Yeah it's a bug that happens when you try to get the comments of an unshared project. Will be fixed. Sorry.

**Comment by TimMcCool** [comment]
the bug should be fixed in an update that I'm about to release (didn't test it tho). Please tell me if the problem still happens

**Comment by crzylemon** [comment]
> pls don't share password

Omg yeah i just noticed
