### ISSUE TITLE
An Error

### ISSUE THREAD

**Issue by Mbrick2** [TimMcCool/scratchattach#2]
I was working on [this](https://replit.com/@Mbrick2/LoveToChangeTitle#main.py) and I got this error

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    session = scratch3.Session(session)
  File "/home/runner/LoveToChangeTitle/venv/lib/python3.8/site-packages/scratch3/_session.py", line 31, in __init__
    self._get_xtoken()
  File "/home/runner/LoveToChangeTitle/venv/lib/python3.8/site-packages/scratch3/_session.py", line 43, in _get_xtoken
    response = json.loads(requests.post(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
 




```

**Comment by TimMcCool** [comment]
Are you sure your session id is valid?

**Comment by TimMcCool** [comment]
Are you sure your session id is valid?

**Comment by Plipplz** [comment]
so I have an issue with importing the ScratchAttach package. Since I am currently on a mac, the pip install command(s) don't work, and when I do: `sudo apt install scratchattach` it just responds with a java runtime error and telling me to install the JVM, which I did but gives me the same error. i have also tried the `os import` and installing the package within the os but that doesn't work either. I really need help as I really want to use scratchattach in my scratch projecct.

**Comment by webdev03** [comment]
@Plipplz try using `pip3` instead of `pip` when you try to pip install

**Comment by TimMcCool** [comment]
https://phoenixnap.com/kb/install-pip-mac
