### ISSUE TITLE
Weird error???

### ISSUE THREAD

**Issue by crzylemon** [TimMcCool/scratchattach#207]
Code:
```
import scratchattach as scratch3

session = scratch3.login("disnottaken_alt", "password") # this worked with all my scratchattach stuff
conn = session.connect_cloud("1018240219") #replace with your project id

client = scratch3.CloudRequests(conn)

@client.request
def searchSort(mode, sort): #called when client receives request
    print("User made request: Mode: " + mode)
    print(scratch3.search_projects(query="query", mode="trending", language="en", limit=40, offset=0)) # testing
    return "Example;Exampler:Example2;Exampler"

@client.event
def on_ready():
    print("Request handler is running")

client.run() #make sure this is ALWAYS at the bottom of your Python file
```
Error:
```
Traceback (most recent call last):
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud.py", line 85, in _connect
    self.websocket.connect(
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException(
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway -+-+- {'content-type': 'text/html', 'content-length': '157', 'connection': 'close', 'date': 'Sun, 12 May 2024 02:31:26 GMT', 'server': 'nginx/1.22.1', 'x-cache': 'Error from cloudfront', 'via': '1.1 858d9017c04d21c6e5b9054c0d1959b4.cloudfront.net (CloudFront)', 'x-amz-cf-pop': 'ATL56-C4', 'x-amz-cf-id': 'g3yArrGOMHTaqQBwRRV_BSo8Q-aJm2xpKcZt2lW3-opP3ItBL1fT3Q=='} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud.py", line 95, in _connect
    self.websocket.connect(
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException(
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway -+-+- {'content-type': 'text/html', 'content-length': '157', 'connection': 'close', 'date': 'Sun, 12 May 2024 02:31:26 GMT', 'server': 'nginx/1.22.1', 'x-cache': 'Error from cloudfront', 'via': '1.1 7ce187769490f932632fd4f1dfed9618.cloudfront.net (CloudFront)', 'x-amz-cf-pop': 'ATL56-C4', 'x-amz-cf-id': '5AGsbz40viBb-Ba3CZwnqn2WJfAhNkUf0KF33ByUSL9yj7DVbyYzzw=='} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\#####\Downloads\scratchattaching\idk\import scratchattach as scratch2.py", line 4, in <module>
    conn = session.connect_cloud("1018240219") #replace with your project id
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\session.py", line 363, in connect_cloud
    return cloud.CloudConnection(username = self._username, session_id = self.session_id, project_id = int(project_id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud.py", line 32, in __init__
    self._connect(cloud_host=cloud_host)
  File "C:\Users\#####\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud.py", line 103, in _connect
    raise(exceptions.ConnectionError)
scratchattach.exceptions.ConnectionError
```

**Comment by TimMcCool** [comment]
Scratch's cloud variables are down entirely at the moment (just like the front page)
