### ISSUE TITLE
get_user() issue

### ISSUE THREAD

**Issue by OniLang-1123t** [TimMcCool/scratchattach#25]
Hi Tim, MadAsTK here. Been having problems with the get_user() function. Here's the error: 

Traceback (most recent call last):
  File "/home/runner/getusr/venv/lib/python3.8/site-packages/scratchattach/_user.py", line 50, in _update_from_dict
    self.id = response["id"]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    user = scratchattach.get_user("username")
  File "/home/runner/getusr/venv/lib/python3.8/site-packages/scratchattach/_user.py", line 534, in get_user
    user.update()
  File "/home/runner/getusr/venv/lib/python3.8/site-packages/scratchattach/_user.py", line 45, in update
    self._update_from_dict(response)
  File "/home/runner/getusr/venv/lib/python3.8/site-packages/scratchattach/_user.py", line 53, in _update_from_dict
    raise(_exceptions.UserNotFound)
scratchattach._exceptions.UserNotFound

It says UserNotFound, even though MadAsTK, what it put there, is a real username. Have a solution?

Frank Was Here

**Comment by OniLang-1123t** [comment]
ok
