### ISSUE TITLE
Cant use requests on a unshared project (1.7.4)

### ISSUE THREAD

**Issue by wvzack** [TimMcCool/scratchattach#289]
I am trying to test a project I am making but I cant as it seems that I have to share the project to be able to use the requests thing on it. My code works fine on shared projects but on unshared it gives: (even if i am logged into the account) (.venv) 
```
pi@raspberrypi:~/Python_Projects/ByteBank $ python3 cloud_requests.py
If you use CloudRequests in your Scratch project, please credit TimMcCool!
Request handler is running
Warning: Caught error in request 'get_all_info' - Full error below
Traceback (most recent call last):
  File "/home/pi/.venv/lib/python3.11/site-packages/scratchattach/cloud_requests.py", line 116, in call_request
    output = req_obj["on_call"](*arguments) # Calls the request function and saves the function's returned data in the output variable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Python_Projects/ByteBank/cloud_requests.py", line 56, in get_all_info
    username = str(client.get_requester()).lower()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.venv/lib/python3.11/site-packages/scratchattach/cloud_requests.py", line 207, in get_requester
    activity = list(
               ^^^^^
  File "/home/pi/.venv/lib/python3.11/site-packages/scratchattach/cloud_requests.py", line 208, in <lambda>
    filter(lambda x: "." + self.last_request_id in x["value"],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

```
Thanks! :)

**Comment by TheCommCraft** [comment]
Is a bug

wvzack ***@***.***> schrieb am So., 17. Nov. 2024, 18:54:

**Comment by TheCommCraft** [comment]
the cloud variable values need to be converted to string

**Comment by TheCommCraft** [comment]
You should pretty much always upgrade the packages to the newest version
but tim needs to fix this first

wvzack ***@***.***> schrieb am So., 17. Nov. 2024, 19:01:

**Comment by wvzack** [comment]
Okay I wasn't upgrading it as I was having problems and I wanted to wait for a stable release.

Thanks!
