### ISSUE TITLE
Cloud Data: Name or service not known

### ISSUE THREAD

**Issue by Sweeistaken** [TimMcCool/scratchattach#302]
(`/home/swee/sweethon` is the location of my venv)
```
swee@peppermint:~$ python bot.py
Bot ACTIVE
Shutting down server...
Traceback (most recent call last):
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 176, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swee/bot.py", line 18, in <module>
    conn.set_var("serveractive" + sn, "1")
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/cloud.py", line 31, in set_var
    super().set_var(variable, value)
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/_base.py", line 205, in set_var
    self.connect()
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/cloud.py", line 27, in connect
    super().connect()
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/_base.py", line 137, in connect
    self.websocket.connect(
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 137, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 191, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 176, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swee/bot.py", line 50, in <module>
    conn.set_var("serveractive" + sn, "0")
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/cloud.py", line 31, in set_var
    super().set_var(variable, value)
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/_base.py", line 205, in set_var
    self.connect()
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/cloud.py", line 27, in connect
    super().connect()
  File "/home/swee/sweethon/lib/python3.11/site-packages/scratchattach/cloud/_base.py", line 137, in connect
    self.websocket.connect(
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 137, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/home/swee/sweethon/lib/python3.11/site-packages/websocket/_http.py", line 191, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known
```
While examining the code of the module, (scratchattach/cloud/cloud.py) I see
```
self.cloud_host = "wss://clouddata.scratch.mit.edu"
```
where clouddata.scratch.mit.edu doesn't actually exist.
```
swee@peppermint:~$ ping clouddata.scratch.mit.edu
ping: clouddata.scratch.mit.edu: Name or service not known
```

**Comment by Sweeistaken** [comment]
After examining Scratch GUI, it seems that it's a scratch problem, the DNS for clouddata.scratch.mit.edu exists (from `dig clouddata.scratch.mit.edu`), but it might be down.

**Comment by TimMcCool** [comment]
Scratch's cloud variables are currently down entirely
