### ISSUE TITLE
error occurs when i try to start up the server

### ISSUE THREAD

**Issue by Timbal5p** [TimMcCool/scratchattach#306]
every time i try to start up the server, an error occurs. Here are the server logs:
```
Thanks for giving credit for CloudRequests!
Exception in thread Thread-3 (_updater):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websocket/_http.py", line 176, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/scratchattach/eventhandlers/cloud_events.py", line 31, in _updater
    self.source_cloud.connect()
  File "/usr/local/lib/python3.12/site-packages/scratchattach/cloud/cloud.py", line 27, in connect
    super().connect()
  File "/usr/local/lib/python3.12/site-packages/scratchattach/cloud/_base.py", line 137, in connect
    self.websocket.connect(
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_http.py", line 137, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_http.py", line 191, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known
```

**Comment by uukelele-scratch** [comment]
Scratch's server is down. There's nothing anyone can do at the moment.

**Comment by FAReTek1** [comment]
you can try to switch to turbowarp for now
