### ISSUE TITLE
Unable to start self-hosted cloud server

### ISSUE THREAD

**Issue by uukelele-scratch** [TimMcCool/scratchattach#307]
```
Traceback (most recent call last):
  File "/home/user/ws_server.py", line 4, in <module>
    server = sa.init_cloud_server(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/scratchattach/eventhandlers/cloud_server.py", line 244, in init_cloud_server
    return TwCloudServer(hostname, port=port, websocketclass=TwCloudSocket)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class TwCloudServer with abstract method _updater
```

I'm unable to start a Cloud Server following the instructions in the docs. Here's my code:
```
import scratchattach as sa

print("starting...")
server = sa.init_cloud_server(
        '0.0.0.0', 3999, # planning to port-forward this externally to 8080, but i might have other programs internally using 8080
        thread=True,
        length_limit=None,
        allow_non_numeric=True,
        blocked_ips = [],
        sync_players=True
)
```

**Comment by TheCommCraft** [comment]
What version are you using? Consider updating scratchattach

**Comment by FAReTek1** [comment]
btw the new changes submitted to github aren't automatically pushed to pypi, a github workflow has to be run first, so when you run it on your end @TheCommCraft, make sure to run it using the latest release on pypi

**Comment by TheCommCraft** [comment]
I know, I didn't change anything

**Comment by TheCommCraft** [comment]
Also, it's not a github action here

**Comment by FAReTek1** [comment]
mb

**Comment by TimMcCool** [comment]
I think I fixed this bug before. in the latest version on pypi, it should be working
