### ISSUE TITLE
Server can't run (Exception in thread Thread-3 (_updater) )

### ISSUE THREAD

**Issue by crzylemon** [TimMcCool/scratchattach#308]
Error:
```
Exception in thread Thread-3 (_updater):
Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_http.py", line 176, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\eventhandlers\cloud_events.py", line 31, in _updater
    self.source_cloud.connect()
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud\cloud.py", line 27, in connect
    super().connect()
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scratchattach\cloud\_base.py", line 137, in connect
    self.websocket.connect(
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_http.py", line 137, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\websocket\_http.py", line 191, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno 11001] getaddrinfo failed
```

Code
```python
import os
import requests
import requests.help

import scratchattach as scratch3

session = scratch3.login("username", "password") # replaced

conn = session.connect_cloud("1072966161")

client = conn.requests()
# normal cloudrequests stuff down here...
```

**Comment by TheCommCraft** [comment]
see #306
