### ISSUE TITLE
can't use cloud variables

### ISSUE THREAD

**Issue by CooperWaNg-py** [TimMcCool/scratchattach#309]
when i try and run

```python
import scratchattach as sa

session = sa.login("username", "password") # note that the username and password are just placeholders
cloud = session.connect_cloud("1114256710")

cloud.set_var("my_var", 5)
``` 
the command line shows this error:
```shell
Traceback (most recent call last):
  File "C:\Users\user\Documents\scratchattach\main.py", line 6, in <module>
    cloud.set_var("variable", value)
                              ^^^^^
NameError: name 'value' is not defined. Did you mean: 'False'?

C:\Users\user\Documents\scratchattach>python main.py
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\websocket\_http.py", line 176, in _get_addrinfo_list
    addrinfo_list = socket.getaddrinfo(
        hostname, port, 0, socket.SOCK_STREAM, socket.SOL_TCP
    )
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 975, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\scratchattach\main.py", line 6, in <module>
    cloud.set_var("my_var", 5)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\scratchattach\cloud\cloud.py", line 31, in set_var
    super().set_var(variable, value)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\scratchattach\cloud\_base.py", line 205, in set_var
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\scratchattach\cloud\cloud.py", line 27, in connect
    super().connect()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\scratchattach\cloud\_base.py", line 137, in connect
    self.websocket.connect(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.cloud_host,
        ^^^^^^^^^^^^^^^^
    ...<4 lines>...
        header = self.header
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\websocket\_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ~~~~~~~^
        url, self.sock_opt, proxy_info(**options), options.pop("socket", None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\websocket\_http.py", line 137, in connect
    addrinfo_list, need_tunnel, auth = _get_addrinfo_list(
                                       ~~~~~~~~~~~~~~~~~~^
        hostname, port_from_url, is_secure, proxy
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\websocket\_http.py", line 191, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno 11001] getaddrinfo failed
``` 

I am running mac so i tried to use my windows pc, but it still didn't work.

more info: python version: 3.13.1
OS: Windows 11, Mac sillicon
scratchattach version: 2.0.9
i hope this is enough infomation

**Comment by FAReTek1** [comment]
scratch cloud variables are down. maybe use turbowarp instead
