### ISSUE TITLE
Can not 'import' / import できない

### ISSUE THREAD

**Issue by 098orin** [TimMcCool/scratchattach#315]
Linuxです。`import scratchatattch`するとこのようになります。
On Linux. `import scratchatattch` will look like this.
```error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/__init__.py", line 4, in <module>
    from .eventhandlers.cloud_server import init_cloud_server
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/eventhandlers/cloud_server.py", line 7, in <module>
    from ..site.user import User
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/site/user.py", line 8, in <module>
    from . import project
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/site/project.py", line 7, in <module>
    from . import user, comment, studio
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/site/comment.py", line 9, in <module>
    from . import session
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/site/session.py", line 34, in <module>
    class Session(BaseSiteComponent):
  File "/home/098-orin/.local/lib/python3.9/site-packages/scratchattach/site/session.py", line 147, in Session
    def new_email_address(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by FAReTek1** [comment]
Odd, because the function signature looks like this:
![image](https://github.com/user-attachments/assets/88e871c6-1770-41a9-a47b-57eebe6b5ff1)
There is no text that says: ```py
-> str | None:
```

**Comment by TheCommCraft** [comment]
Your python is old. You should update it

faretek ***@***.***> schrieb am Sa., 28. Dez. 2024, 15:16:

**Comment by TheCommCraft** [comment]
> Odd, because the function signature looks like this:
> ![image](https://github.com/user-attachments/assets/88e871c6-1770-41a9-a47b-57eebe6b5ff1)
> There is no text that says: `-> str | None:`

You must have changed it recently

**Comment by 098orin** [comment]
新しいpythonをインストールすることで解決されました。ありがとうございます。
It was resolved by installing a new python. thank you.
