### ISSUE TITLE
Turbowarp error for AttributeError: 'TwCloudRequests' object has no attribute 'respond_in_thread'

### ISSUE THREAD

**Issue by lololol456780** [TimMcCool/scratchattach#32]
I'm using repl, and it keeps coming up with that error for some reason.
Full error:
Traceback (most recent call last):
  File "main.py", line 569, in <module>
    client.run()
  File "/home/runner/TechnologicalLiveProcesses/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 334, in run
    self._run(events, data_from_websocket=True)
  File "/home/runner/TechnologicalLiveProcesses/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 295, in _run
    self.call_request(request_id, req_obj, arguments)
  File "/home/runner/TechnologicalLiveProcesses/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 55, in call_request
    if not self.respond_in_thread:
AttributeError: 'TwCloudRequests' object has no attribute 'respond_in_thread'
(this was a test project)

**Comment by lololol456780** [comment]
nvm fixed

**Comment by lololol456780** [comment]
nvm its broken again :/

**Comment by lololol456780** [comment]
whenever it recieves a request it does the error

**Comment by lololol456780** [comment]
whenever it recieves a request it does it

**Comment by jimjamgithub** [comment]
hmmmm very strange. I see you are using replit. it could have something to do with that

**Comment by TimMcCool** [comment]
Update scratchattach. There was a bug in v1.0, it is fixed now
