### ISSUE TITLE
Cloud Vars not working

### ISSUE THREAD

**Issue by AxeToOcelot** [TimMcCool/scratchattach#59]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 71, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannah/Documents/Test.py", line 5, in <module>
    Connect = Session.connect_cloud("782892053")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_session.py", line 247, in connect_cloud
    return _cloud.CloudConnection(username = self._username, session_id = self.session_id, project_id = int(project_id))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 22, in __init__
    self._connect(cloud_host=cloud_host)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 78, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError

**Comment by mas6y6** [comment]
I head this issue before

**Comment by AxeToOcelot** [comment]
And What was the fix

**Comment by mas6y6** [comment]
Umm its hard

**Comment by mas6y6** [comment]
You need to reset your computer not restart reset

**Comment by TimMcCool** [comment]
This most likely means websocket's don't work in your Python environment. Can I see your code?

**Comment by AxeToOcelot** [comment]
I did 

> pip install scratchattach

 in my mac terminal

and then did this in python

import scratchattach as scratch3
session = scratch3.login("glen080", "i put in my password")
conn = session.connect_cloud("782892053")

and here is the project

https://scratch.mit.edu/projects/782892053/

i was trying to do something to get your username and show how much mail you have

**Comment by tt-thoma** [comment]
Don't reset your computer, find a tutorial on how to reinstall your SSL certificates. Also may ba a Scratch issue

**Comment by AxeToOcelot** [comment]
I fixed it with replit thanks!
