### ISSUE TITLE
Unable to create session

### ISSUE THREAD

**Issue by sahilcodes-max** [TimMcCool/scratchattach#61]
For some reason, whenever I try to create a session, I get this error.
`Traceback (most recent call last):
  File "C:\Users\chopr\OneDrive\Documents\coding\Python\scratchattach.py", line 1, in <module>
    import scratchattach as scratch3
  File "C:\Users\chopr\OneDrive\Documents\coding\Python\scratchattach.py", line 2, in <module>
    session = scratch3.login("shivitests", "******") # blurred for github
AttributeError: partially initialized module 'scratchattach' has no attribute 'login' (most likely due to a circular import)`

**Comment by sahilcodes-max** [comment]
nvm fixed it
