### ISSUE TITLE
Cloud Requests getting Error during request.

### ISSUE THREAD

**Issue by speedwaysingapore** [TimMcCool/scratchattach#71]
### Hello
I am making something on replit for a Scratch Project that I am making and it uses cloud requests.
It does work well after a few times but then a few requests later, I get this:

Traceback (most recent call last):
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/scratchattach/_cloud.py", line 287, in _update
    data = self.connection.websocket.recv().split('\n')
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/scratchattach/_cloud.py", line 71, in _connect
    self.websocket.connect(
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 147, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/scratchattach/_cloud.py", line 298, in _update
    self.connection._connect(cloud_host=self.connection.cloud_host)
  File "/home/runner/Live-Follower-Count-Server/venv/lib/python3.10/site-packages/scratchattach/_cloud.py", line 78, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError

Are there going to be fixes soon or in the next update because this project is somewhat important.
`Don't know if this is a duplicate or not.`

**Comment by speedwaysingapore** [comment]
Code:
`... @client.event
def on_ready():
  print("Handler is running currently!")
@client.request
def leaderboard(region, cat, page):
  #needs splitting
  print("requesting...")
  response = requests.get(f"https://scratchdb.lefty.one/v3/user/rank/{region}/{cat}/{page}").text
  data = str(json.loads(response))
  print(data)
def run():
  client.run(data_from_websocket=True)`

**Comment by speedwaysingapore** [comment]
If you don't do data_from_websocket=True, it can still occur but it's a low chance of getting that.

**Comment by TimMcCool** [comment]
looks like the websocket somehow lost connection. Where are you running the python code?

**Comment by TimMcCool** [comment]
replit's ip addresses are not banned from scratch's cloud websockets. But sometimes replit is buggy. Try running `kill 1` in the shell tab if your repl

**Comment by TimMcCool** [comment]
replit's ip addresses are not banned from scratch's cloud websockets. But sometimes replit is buggy. Try running `kill 1` in the shell tab of your repl
