### ISSUE TITLE
Import error?

### ISSUE THREAD

**Issue by 1and1is3** [TimMcCool/scratchattach#77]
When i try to import SA, i get this error:
`Traceback (most recent call last):
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libz.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import scratchattach as scratch3
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/scratchattach/__init__.py", line 1, in <module>
    from ._cloud import *
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/scratchattach/_cloud.py", line 2, in <module>
    from numpy import var
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/runner/scratch-image/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/home/runner/scratch-image/venv/bin/python"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libz.so.1: cannot open shared object file: No such file or directory`

I'm using replit.

**Comment by TimMcCool** [comment]
Try running `kill 1` in the `Shell` tab of your repl

**Comment by 1and1is3** [comment]
Thanks, now it does work!
I have another question: I made an [Image Render](https://scratch.mit.edu/projects/851049923/) a while ago, but sometimes (especially in high res) a piece of the data gets lost, completely destroying the image. Is there any way to check if all the data is correct?

**Comment by TimMcCool** [comment]
scratchattach's cloud requests are supposed to detect that, maybe that isn’t working properly. You could check in the Scratch project if the length of the received data is valid

**Comment by 1and1is3** [comment]
ok, thank you for helping.
