### ISSUE TITLE
Fail in connecting to cloud variables of project

### ISSUE THREAD

**Issue by GitbyteMaster** [TimMcCool/scratchattach#96]
My project script is just composed of importing the module, logging in, and using `connect_cloud()`, like below.
```python
import scratchattach as scratch3

session = scratch3.login("*", "*")
conn = session.connect_cloud("845041108")
```
And, immediately, I'm flooded with errors:
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scratchattach/_cloud.py", line 72, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scratchattach/_cloud.py", line 81, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/*/Desktop/SORA/Cloud Handler.py", line 4, in <module>
    conn = session.connect_cloud("845041108")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scratchattach/_session.py", line 248, in connect_cloud
    return _cloud.CloudConnection(username = self._username, session_id = self.session_id, project_id = int(project_id))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scratchattach/_cloud.py", line 23, in __init__
    self._connect(cloud_host=cloud_host)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scratchattach/_cloud.py", line 88, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError
```
I have no experience with the `websocket` modules and things like that, so I'm kind of lost here. Could you help?

**Comment by TheCommCraft** [comment]
It happens sometimes, even on the scratch website, but there there is an automatic reconnect if it disconnects

**Comment by TimMcCool** [comment]
Does this happen everytime you run the code, or only sometimes?

**Comment by mas6y6** [comment]
I had this issue before but I fixed somehow

**Comment by GitbyteMaster** [comment]
I always do

**Comment by mas6y6** [comment]
Try reinstalling websocket by using

```
pip uninstall websocket-client
pip install websocket-client
```

**Comment by programORdie2** [comment]
Or just: `
pip install -U websocket-client
`

**Comment by TheCommCraft** [comment]
Or 'pip install --force-reinstall websocket-client'

programORdie2 ***@***.***> schrieb am Do., 13. Juli 2023,
09:31:

**Comment by mas6y6** [comment]
Or try reinstalling python

**Comment by GitbyteMaster** [comment]
Alright, trying out your suggestions now. Thanks!

**Comment by GitbyteMaster** [comment]
And.. nothing.

**Comment by GitbyteMaster** [comment]
My error's a little different, now, though.
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 67, in _connect
    self.websocket.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websocket/_http.py", line 247, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 82, in _connect
    timeout=timeout
NameError: name 'timeout' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/*/Desktop/SORA/Cloud Handler.py", line 4, in <module>
    conn = session.connect_cloud("845041108")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_session.py", line 248, in connect_cloud
    return _cloud.CloudConnection(username = self._username, session_id = self.session_id, project_id = int(project_id))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 24, in __init__
    self._connect(cloud_host=cloud_host)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_cloud.py", line 85, in _connect
    raise(_exceptions.ConnectionError)
scratchattach._exceptions.ConnectionError
```

**Comment by programORdie2** [comment]
Sometimes I have the same error, but usually it passes after restarting the code a few times.

**Comment by GitbyteMaster** [comment]
Doesn't work.

**Comment by programORdie2** [comment]
oh 😥

**Comment by GitbyteMaster** [comment]
What do I now now?

**Comment by programORdie2** [comment]
idk, i'm not very good in using websocket-things.

**Comment by GitbyteMaster** [comment]
Say, what platform are you working on? Windows, Mac, etc.

**Comment by programORdie2** [comment]
windows

**Comment by GitbyteMaster** [comment]
I'm using a Mac. Could that be my problem?

**Comment by programORdie2** [comment]
Hmm, i don't think so ...

**Comment by mas6y6** [comment]
I am on mac as will it working fine umm

**Comment by mas6y6** [comment]
Ok try this
```
pip uninstall websocket-client
```
```
pip uninstall numpy
```
```
pip uninstall bs4
```
```
pip uninstall beautifulsoup4
```

and run this

```
pip install scratchattach
```

**Comment by mas6y6** [comment]
I Hope that helps if not I don't know what to say

**Comment by GitbyteMaster** [comment]
Alright, thank you!

**Comment by GitbyteMaster** [comment]
Well, that didn't work either. :(

**Comment by programORdie2** [comment]
Try using another account?

**Comment by GitbyteMaster** [comment]
I’m starting to believe using a Mac is the problem. What do you think?

**Comment by mas6y6** [comment]
No I am on mac and its working fine

**Comment by GitbyteMaster** [comment]
Then what do I do??

**Comment by mas6y6** [comment]
iDk

**Comment by RC9910-Scratch** [comment]
What macOS version are you using/What are you using to run the scripts?

**Comment by GitbyteMaster** [comment]
A MacBook Air, with the M1 chip.

**Comment by GitbyteMaster** [comment]
Got my hands back opn Windows, where it does indeed work. Should I close this?

**Comment by RC9910-Scratch** [comment]
If the problem is resolved i think you can

**Comment by GitbyteMaster** [comment]
k
