### ISSUE TITLE
[Scratch API studio invite ratelimit] Why sometime have this problem

### ISSUE THREAD

**Issue by Profrozer** [TimMcCool/scratchattach#98]
So recently I made a program and sometime it give me (See the bottom):
Traceback (most recent call last):
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\site-packages\scratchattach\_studio.py", line 142, in invite_curator
    ).json()
      ^^^^^^
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\nicho\OneDrive\Desktop\Scratch\StudioInvites.py", line 18, in <module>
    studio.invite_curator(username)
ator
    raise(_exceptions.Unauthorized)
scratchattach._exceptions.Unauthorized

I run it on my VS Code

**Comment by TimMcCool** [comment]
you have to use session.connect_studio to get the studio if you want to use methods that require authentication (not scratch3.get_studio)

**Comment by programORdie2** [comment]
I did use the connect_studio function and after about 100 people the invites I got the same error. I think it is because scratch blocks your IP for a while if you make too many requests.

**Comment by TimMcCool** [comment]
Oh, yes, there's a ratelimit for inviting curators. If you invite more than 100 people within a few minutes, it will give you an error. The same will happen if you use the Scratch website to invite 100+ people withing a few minutes

**Comment by TheCommCraft** [comment]
So remove the issue label and replace it with a scratch api issue label

**Comment by Profrozer** [comment]
> So remove the issue label and replace it with a scratch api issue label

how?

**Comment by Profrozer** [comment]
> Oh, yes, there's a ratelimit for inviting curators. If you invite more than 100 people within a few minutes, it will give you an error. The same will happen if you use the Scratch website to invite 100+ people withing a few minutes

ohh, that's why!!!!

**Comment by TheCommCraft** [comment]
Profrozer not you

Profrozer ***@***.***> schrieb am Mi., 21. Juni 2023, 08:44:

**Comment by programORdie2** [comment]
And how long do you need to wait before you got unblocked?
